global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres-exporter-teams'
    static_configs:
      - targets: ['postgres-exporter-teams:9187']

  - job_name: 'postgres-exporter-requests'
    static_configs:
      - targets: ['postgres-exporter-requests:9187']

  - job_name: 'postgres-exporter-auth'
    static_configs:
      - targets: ['postgres-exporter-auth:9187']

  - job_name: 'postgres-exporter-calendar'
    static_configs:
      - targets: ['postgres-exporter-calendar:9187']

  - job_name: 'postgres-exporter-competitions'
    static_configs:
      - targets: ['postgres-exporter-competitions:9187']

  - job_name: 'postgres-exporter-match-comments'
    static_configs:
      - targets: ['postgres-exporter-match-comments:9187']

  - job_name: 'postgres-exporter-audit'
    static_configs:
      - targets: ['postgres-exporter-audit:9187']