openapi: 3.0.3
info:
  title: Audit Service API
  version: 1.0.0
  description: Serviço responsável por registrar e auditar eventos da plataforma.
paths:
  /api/v1/campus/{campus_code}/logs/:
    get:
      operationId: v1_campus_logs_list
      description: Retorna uma lista paginada de todos os logs de auditoria associados
        ao `campus_code` fornecido na URL.
      summary: Lista os logs de auditoria de um campus
      parameters:
      - in: path
        name: campus_code
        schema:
          type: string
        description: O código do campus para filtrar os logs.
        required: true
      tags:
      - Auditoria
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '403':
          description: Permissão negada. Apenas organizadores podem acessar.
  /api/v1/campus/{campus_code}/logs/{id}/:
    get:
      operationId: v1_campus_logs_retrieve
      description: Retorna os detalhes de um único log de auditoria, identificado
        pelo seu ID.
      summary: Obtém um log de auditoria específico
      parameters:
      - in: path
        name: campus_code
        schema:
          type: string
        description: O código do campus ao qual o log pertence.
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this log.
        required: true
      tags:
      - Auditoria
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '403':
          description: Permissão negada. Apenas organizadores podem acessar.
        '404':
          description: Log não encontrado.
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
